### PR TITLE
Forecast #42

### PR DESCRIPTION
**Pull request by sylvainschmitt**

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
In a perfect world unit testing shouldn't throw warnings or messages. I removed some messages from ANN and SVM, and I still didn't figure how to remove outputs from GBM to have a clear console (not the trace of the algorithme).

**Comment by sylvainschmitt** [comment]
Tests are all good, great work @lukasbaumbach but if possible it would be good to remove the numerous warnings of test_parallel_SSDM, test_project_SSDM, and test_stack_modelling. Which in fact are always the same warning, I'll have a quick look. And the unit testing is a bit too long (270.1s) due to test_parallel_SSDM during alone 154.2s. We should look if we can't reduce the data used here to speed up unit testing.

**Comment by sylvainschmitt** [comment]
Last but not least, I'm fighting with Travis to work with geobuffrer. Two things, I try to avoid suggest and you should always use require to check that the user installed the suggest and not assume he did (see my commit). Moreover, always avoid non CRAN packages as they are less stable. Maybe we can do an exception for geobuffer. But it's a bit a pain.. to get it working with Travis automatic checks.

**Comment by sylvainschmitt** [comment]
Anyway, once again cool and great works (I had a look to parallelization, it seems awesome). I think we are one "cosmetic" now and that the new version will be ready to be published soon.

**Comment by lukasbaumbach** [comment]
All set for merging?

**Comment by sylvainschmitt** [comment]
Absolutely ! Good job.

**Pull request merged**
